# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: kubeapps-apis
      image: docker.io/bitnami/kubeapps-apis:2.12.1-debian-12-r0
    - name: kubeapps-apprepository-controller
      image: docker.io/bitnami/kubeapps-apprepository-controller:2.12.1-debian-12-r0
    - name: kubeapps-asset-syncer
      image: docker.io/bitnami/kubeapps-asset-syncer:2.12.1-debian-12-r0
    - name: kubeapps-dashboard
      image: docker.io/bitnami/kubeapps-dashboard:2.12.1-debian-12-r0
    - name: kubeapps-oci-catalog
      image: docker.io/bitnami/kubeapps-oci-catalog:2.12.1-debian-12-r0
    - name: kubeapps-pinniped-proxy
      image: docker.io/bitnami/kubeapps-pinniped-proxy:2.12.1-debian-12-r0
    - name: nginx
      image: ghcr.io/sap/kubeapps/bitnami-deprecated-nginx:1.29.1
    - name: oauth2-proxy
      image: ghcr.io/sap/kubeapps/bitnami-deprecated-oauth2-proxy:7.12.0
apiVersion: v2
appVersion: DEVEL
dependencies:
- condition: packaging.flux.enabled
  name: redis
  repository: file://./charts/redis
  version: 23.0.2
- condition: packaging.helm.enabled
  name: postgresql
  repository: file://./charts/postgresql
  version: 17.0.0
- name: common
  repository: file://./charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Kubeapps is a web-based UI for launching and managing applications on Kubernetes. It allows users to deploy trusted applications and operators to control users access to the cluster.
home: https://sap.com
icon: https://sap.github.io/kubeapps/img/chart-asset/kubeapps-stack-220x234.png
keywords:
- helm
- dashboard
- service catalog
- deployment
kubeVersion: '>=1.25.0-0'
maintainers:
- name: Siegfried Kiermayer
- name: SAP SE All Rights Reserved.
  url: https://sap.com
name: kubeapps
sources:
- https://github.com/sap/kubeapps/
version: 18.0.0
