apiVersion: v1
entries:
  kubeapps:
    - name: kubeapps
      version: 18.0.0
      apiVersion: v2
      appVersion: 3.0.0-rc10
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc10/kubeapps-18.0.0.tgz
      created: "2025-12-18T12:12:34Z"
      digest: d694ff99ae51cc785a4904fbfdf8ad0bc7fcee595b53445cebc3de2329ee7b96
    - name: kubeapps
      version: 3.0.0-rc12
      apiVersion: v2
      appVersion: ""
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc12/kubeapps-3.0.0-rc12.tgz
      created: "2025-12-18T14:02:37Z"
      digest: 3b267836fac556f72f6c89c7726af8352373ec9782ed2c506e21dd64db1bd314
    - name: kubeapps
      version: 18.0.0
      apiVersion: v2
      appVersion: 3.0.0-rc6
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc6/kubeapps-18.0.0.tgz
      created: "2025-12-18T12:12:35Z"
      digest: 87a4d2ccc9a7eaa1e5e2a4336aed94a7237ad2889e21b5cf92e259270a4fd265
    - name: kubeapps
      version: 18.0.0
      apiVersion: v2
      appVersion: 3.0.0-rc7
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc7/kubeapps-18.0.0.tgz
      created: "2025-12-18T12:12:35Z"
      digest: 87cdaaebda5759dc941ae76570f4fa8f77fd1e2f23e0c3ece299eece048b19b2
    - name: kubeapps
      version: 18.0.0
      apiVersion: v2
      appVersion: 3.0.0-rc8
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc8/kubeapps-18.0.0.tgz
      created: "2025-12-18T12:12:36Z"
      digest: 55989b3a984b7bbe1b9cddf69c97a2e8c1dc352a46b3067eadb224c33922e952
    - name: kubeapps
      version: 18.0.0
      apiVersion: v2
      appVersion: 3.0.0-rc9
      description: Kubeapps is a web-based UI for launching and managing applications on
      home: https://sap.com
      kubeVersion: '>=1.25.0-0'
      sources: []
      urls:
        - https://github.com/SAP/kubeapps/releases/download/v3.0.0-rc9/kubeapps-18.0.0.tgz
      created: "2025-12-18T12:12:36Z"
      digest: 5578af880d6042a45a123579e8172ba0e2d9fa85ce53ea522c9599bdcf933a6a
