entries:
  kubeapps:
    - name: "null"
      version: 17.1.1
      urls:
        - "null"
      created: "null"
      digest: "null"
    - name: "null"
      version: 18.0.0
      urls:
        - "null"
      created: "null"
      digest: "null"
    - name: "null"
      version: 18.0.0
      urls:
        - "null"
      created: "null"
      digest: "null"
